# Generated by Django 3.2.3 on 2021-07-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_auto_20210614_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='imagenNoticia',
        ),
    ]
